### PR TITLE
 Add a common spark interface, remove internal casts 

### PR DESCRIPTION
**Pull request by Alwinfy**
(Drafted since it depends on a very minor change in #3457)

### CODE REVIEW

**Comment by williewillus** [comment]
what's the point of joining them together?

**Comment by Alwinfy** [comment]
Mostly for the sake of keeping spark dyes dry

**Comment by williewillus** [comment]
remind me when 1.17 comes around, this actually is backward incompatible since it changes param types/moves methods around

**Comment by williewillus** [comment]
wtf this is confirmed go away

**Comment by williewillus** [comment]
@Alwinfy can you rebase on 1.17-fabric?

**Pull request merged**
